<template>
  <svg
    width="18"
    height="18"
    viewBox="0 0 18 18"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <rect
      x="3.00003"
      y="3"
      width="12"
      height="4.5"
      rx="2"
      stroke="black"
      stroke-width="1.5"
      stroke-linecap="round"
      stroke-linejoin="round"
      :style="customStyle"
    />
    <rect
      x="3.00003"
      y="3"
      width="12"
      height="4.5"
      rx="2"
      stroke="white"
      stroke-opacity="0.2"
      stroke-width="1.5"
      stroke-linecap="round"
      stroke-linejoin="round"
      :style="customStyle"
    />
    <rect
      x="3.00003"
      y="10.5"
      width="12"
      height="4.5"
      rx="2"
      stroke="black"
      stroke-width="1.5"
      stroke-linecap="round"
      stroke-linejoin="round"
      :style="customStyle"
    />
    <rect
      x="3.00003"
      y="10.5"
      width="12"
      height="4.5"
      rx="2"
      stroke="white"
      stroke-opacity="0.2"
      stroke-width="1.5"
      stroke-linecap="round"
      stroke-linejoin="round"
      :style="customStyle"
    />
  </svg>
</template>
<script setup lang="ts">
defineProps<{
  customStyle?: Record<string, string>;
}>();
</script>

